dictionaries = ["en_us"]
words = [
    "Apato",
    "Backwego",
    "Duolingo",
    "Eiendom",
    "Giertsen",
    "Naphat",
    "Rieber",
    "Tormod",
    "Tromsø",
    "Vannteknologi",
    "Vaskerelven",
    "Visito",
    "aisummary",
    "apatoad",
    "applenes",
    "appleness",
    "hottesttechyoumustknow",
    "linkedin",
    "mfrac",
    "mrow",
    "msup",
    "naphatsite",
    "neuralnetworksageometricinterpretation",
    "pearness",
    "perceptrons",
    "programmatically",
    "templ",
    "templcomponents",
    "templutils",
    "twmerge",
    "whoisthisman",
]
include_paths = ["web/**/*.templ"]
